### ISSUE TITLE
Convert transaction_hash, block_hash datatype to text

### ISSUE THREAD

**Issue by orkunkl** [iov-one/block-metrics#20]
`transaction_hash`, `block_hash field` should be `text` (not bytes) so we can search easily

**Comment by aditya9026** [comment]
https://www.compose.com/articles/faster-operations-with-the-jsonb-data-type-in-postgresql/

**Comment by orkunkl** [comment]
I think that link is more related to https://github.com/iov-one/block-metrics/issues/19

**Comment by aditya9026** [comment]
@orkunkl @antoineherzog 
- we're synching data from RPC endpoint
- for transaction_hash and block_hash field the data is coming in form of byte
- In order to save the data Into the api app(heroku database) we need to keep the same data type of columns, otherwise, the validation failed and data will not we saved from iov mainet to api app.
- In order to solve this problem, either we need to change the data type on both side database or while syncing into our heroku database we need to convert the byte format to text format,
- If we need to convert the byte format to text we should know which encoding is used for byte format

**Comment by orkunkl** [comment]
I just don't get what causes the inconsistency between api app and the database?

**Comment by orkunkl** [comment]
Do you want to start implementing the task or should I?

**Comment by aditya9026** [comment]
@orkunkl you can start if you get this, for my understanding we need to know the encoding first. data is saved in iov mainnet already in bytea format.
let me know if you are getting my point.

**Comment by orkunkl** [comment]
There you go: https://github.com/iov-one/block-metrics/blob/block-explorer/pkg/metrics/json.go#L11-L26

**Comment by orkunkl** [comment]
Moved to https://github.com/iov-one/quick-block-explorer/issues/9
